### PR TITLE
fix(angular): Cannot set property 'classNames' of undefined

### LINKED ISSUE #4130: Angular: Cannot set property 'classNames' of undefined
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.4.8
* Platform/Target and Browser Versions: Windows, CHROME
* Live Link or JSFiddle/Codepen or website with isssue: https://stackblitz.com/edit/angular-swiper-classname?file=src/app/app.component.ts

### What you did
Create new slide after swiper init, by button

### Expected Behavior
Create slide like usual

### Actual Behavior
Slide create, but in console write: Cannot set property 'classNames' of undefined
And the usual slider operation breaks down

### PR DESCRIPTION
**Pull request by vltansky**
closes #4130

### CODE REVIEW

File: src/types/swiper-events.d.ts [hunk 1]
```diff
@@ -223,6 +223,14 @@ export interface SwiperEvents {
...
    */
   _slideClass?: (swiper: Swiper, el: HTMLElement, classNames: string) => void;
+
+  /**
+   * INTERNAL: Event will fired after setting CSS classes on all swiper slides
+   */
+  _slideClasses?: (
+    swiper: Swiper,
+    slides: { el: HTMLElement; classNames: string; index: number }[],
+  ) => void;
```
Comment (vltansky) [inline src/types/swiper-events.d.ts:233]: I use it in angular to rerender class names. So I think it will be better to rerender it once, instead of on every slide.

**Comment by nolimits4web** [comment]
Thanks!
