### PR TITLE
fix(angular): setElement call updateInitSwiper bug

### LINKED ISSUE #5291: Error in swiper_angular.js in version 7.3.1 or 7.3.2
### Check that this is really a bug

- [X] I confirm

### Reproduction link

no reproduction link

### Bug description

An error occurs at line 729 (version 7.3.0) when you try to run

if (changedParams.scrollbar) {
                if (this.scrollbar &&
                    typeof this.scrollbar !== 'boolean' &&
                    this.scrollbar.el &&
                    scrollbar &&
                    !scrollbar.el) {
                    this.updateParameter('scrollbar', this.scrollbar);
                    scrollbar.init();
                    scrollbar.updateSize();
                    scrollbar.setTranslate();
                }
                else {
                    scrollbar.destroy();   // -------->  here!
                    scrollbar.el = null;
                }
            }

because the scrollbar object is undefined, but changedParams.scrollbar is true.

This does not happen until version 7.3.0 .-

In my project there are 3 swipers, but none use scrollbar, I don't even read the Scrollbar object from swiper.

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Swiper version

7.3.1 or 7.3.2

### Platform/Target and Browser Versions

Windows 10 Pro, Chrome Versión 96.0.4664.93 (Build oficial) (64 bits)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

### PR DESCRIPTION
**Pull request by vltansky**
fixes #5291

### CODE REVIEW

File: src/angular/src/swiper.component.ts [hunk 1]
```diff
@@ -459,7 +459,8 @@ export class SwiperComponent implements OnInit {
   ) {}
 
   private _setElement(el: ElementRef, ref: any, update: string, key = 'el') {
-    if (ref && el && el.nativeElement) {
+    if (!ref && !el) return;
+    if (el.nativeElement) {
```
Comment (ha-akelius) [inline src/angular/src/swiper.component.ts:463]: I have error in this line 
`core.js:6486 ERROR TypeError: Cannot read properties of undefined (reading 'nativeElement')`
can we convert this line to 
`if(el?.nativeElement) {`
