### PR TITLE
Fix: Ensure the Zoom module's  array is cleared onTouchEnd

### LINKED ISSUE #7304: Long pressing on a zoomable slide breaks zoom interactions for that slide
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos/400-zoom/core

### Bug description

On mobile, if you long press an image on a given slide (e.g. to copy or save the image), you can no longer zoom in and out of that slide until you leave the slide and come back.

### Expected Behavior

You should be able to long press on an image to copy/save it, and continue to interact with the slide.

### Actual Behavior

Zoom gets stuck in the last state.

### Swiper version

11.0.6

### Platform/Target and Browser Versions

iOS Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

### PR DESCRIPTION
**Pull request by broox**
This fixes an issue in which long pressing a slide's image left the zoom module in a bad state.

Closes #7304

### CODE REVIEW

File: src/modules/zoom/zoom.mjs [hunk 1]
```diff
@@ -28,7 +28,6 @@ export default function Zoom({ swiper, extendParams, on, emit }) {
   let isScaling = false;
   let fakeGestureTouched;
   let fakeGestureMoved;
-  let preventZoomOut;
```
Comment (broox) [inline src/modules/zoom/zoom.mjs:31]: 🧹 this was simply unused.

File: src/modules/zoom/zoom.mjs [hunk 2]
```diff
@@ -378,6 +377,7 @@ export default function Zoom({ swiper, extendParams, on, emit }) {
   }
   function onTouchEnd() {
     const zoom = swiper.zoom;
+    evCache.length = 0;
```
Comment (broox) [inline src/modules/zoom/zoom.mjs:380]: On Chrome for iOS, long pressing a slide's image would leave the previous touch event in the `evCache` array.
This ensure that `evCache` is cleared `onTouchEnd`.

**Comment by nolimits4web** [comment]
Merged, thank you!
