### PR TITLE
fix: add missing types

### LINKED ISSUE #3912: Why NavigationMethods doesn't export init() and destory()?
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 6.3.4
* Platform/Target and Browser Versions: Chrome or Firefox. Not specific.
* Live Link or JSFiddle/Codepen or website with isssue: Nothing.

### Expected Behavior
I expect that typed file exports NavigationMethods is containing `init()` and `destory()`.

Did I miss something? Are the methods like private? Sorry for this, I'm kind of new to reading program.

### PR DESCRIPTION
**Pull request by vltansky**
closes #3912
related #3918

### CODE REVIEW

File: src/types/components/controller.d.ts [hunk 1]
```diff
@@ -1,6 +1,8 @@
 import Swiper from '../swiper-class';
 
-export interface ControllerMethods {}
+export interface ControllerMethods {
+  control?: Swiper;
```
Comment (vltansky) [inline src/types/components/controller.d.ts:4]: Is it the right place for it?
e.g Vue:
```js
if (needControllerInit) {
    swiper.controller.control = currentParams.controller.control;
  }
```

**Comment by nolimits4web** [comment]
Thanks! I added some docs and moved keyboard and mouse wheel events to relevant modules
